lutzcc1/homet

- config/routes.rb
hey guys I refactor the routes and corrected a minor issue. The models in resources should be set in plural and we set them in singular. Fore example, it must be `resources :meals` instead of `resources :meal`
> Refactor routes

- app/views/layouts/application.html.erb
- config/initializers/devise.rb
Hey guys, I changed the sender email and added the sign up and log in button to the nav bar!
> Add devise functionality

- Gemfile
- Gemfile.lock
- app/models/meal.rb
- db/seeds.rb
Hey guys the seed file is ready if you want to make some testing.
Reviews and bookings depend on the user's id so every time this file is run the db needs to be empty so that it can start assigning ids from 0. If for any reason you need to run db:seed more than once, first drop and recreate your db.
> seed file created

- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
Hey guys, I created the bookings controller with index, show, edit, update and destroy methods. I also added the view file for index.
> Show bookings made by user

- app/controllers/bookings_controller.rb
To include the before_Action piece that Luis had in his meals controller.
> Updated bookings controller

- app/controllers/meals_controller.rb
- app/controllers/reviews_controller.rb
- app/views/meals/_booking_form.html.erb
- app/views/meals/show.html.erb
- app/views/reviews/index.html.erb
- app/views/reviews/new.html.erb
- config/routes.rb
- test/controllers/meals_controller_test.rb
- test/controllers/reviews_controller_test.rb
Created reviews controller and view. Created a meal Show view so user can submit booking form but is not working since I didn't create a Booking Controller.
> Create and show reviews

- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- test/controllers/bookings_controller_test.rb
Show view for bookings...showing details of a particular booking. I included user name of the booking, meal name and number of eaters.
> Added show view for bookings

- app/views/meals/home.html.erb
> homepage correction

- app/controllers/bookings_controller.rb
- app/controllers/meals_controller.rb
- app/views/layouts/application.html.erb
Hey guys, added the manage my bookings button and sign-out for active users.
> Enhance for active users

- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
- app/views/meals/home.html.erb
Hey guys, 
Further enhancing the time/user aspect of show bookings. Now they are directed to diffrent shows if the booking is past or upcoming and if they have added a review or not for past bookings. 
Let me know your thoughts!
> Add time to bookings

- app/controllers/meals_controller.rb
- app/controllers/pages_controller.rb
- app/views/meals/home.html.erb
- app/views/meals/offered.html.erb
- app/views/meals/partials/_create_edit_form.html.erb
You can now view the meals you offered.
I'm keeping it super simple, just making it work. In other words, it looks ugly
> Show offered meals

- app/controllers/bookings_controller.rb
- app/controllers/meals_controller.rb
- app/controllers/pages_controller.rb
- app/views/bookings/eaters.html.erb
- app/views/meals/home.html.erb
- app/views/meals/offered.html.erb
- app/views/meals/partials/_create_edit_form.html.erb
Hey guys, with this now you can view the bookings that each one of the meals you offer has
> Show meals bookings

- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/meals_controller.rb
- app/controllers/reviews_controller.rb
- app/views/meals/_booking_form.html.erb
- app/views/meals/show.html.erb
Added new booking into the meal view.
> Create booking in meal view

- app/controllers/bookings_controller.rb
- app/views/bookings/show.html.erb
- app/views/layouts/application.html.erb
- app/views/meals/offered.html.erb
> Mvp test changes

- Gemfile
- Gemfile.lock
- app/controllers/meals_controller.rb
- app/models/meal.rb
- app/views/meals/partials/_create_edit_form.html.erb
- app/views/meals/show.html.erb
- db/migrate/20200504134920_add_open_hours_to_meals.rb
- db/schema.rb
Hey guys, with this our meals now have "open hours". This are set on meals creation and can be modified latter
> Add open hours

- app/controllers/meals_controller.rb
- app/views/meals/home.html.erb
> search bar added

- app/controllers/application_controller.rb
- app/controllers/users/confirmations_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/controllers/users/unlocks_controller.rb
- config/routes.rb
Require users to sign-up/log in before making a booking. Also added functionality to redirect user back to the previous screen if prompted to log in.
> Improve sign up

- app/views/meals/_booking_form.html.erb
- db/seeds.rb
Sorry this is late guys! I don't think it's perfect, but it works at least! 
Will get Cloudinary done today too :)
> Add new seed with booking and meal open times and close times.

- app/views/meals/home.html.erb
everything aligned
the big empty square at the bottom is the map which we cannot see as it has no valid address to geolocalize
> updated homepage aligned NO MORE DIAGONAL

- app/views/meals/offered.html.erb
- db/schema.rb
I only added new links to the offered views. Fooders can now edit, view bookings and view the actual meal
> update links in offered meals

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/meals_controller.rb
- app/models/meal.rb
- app/views/bookings/index.html.erb
- app/views/meals/partials/_create_edit_form.html.erb
- app/views/meals/show.html.erb
- config/environments/development.rb
- config/storage.yml
- db/migrate/20200506064746_create_active_storage_tables.active_storage.rb
- db/schema.rb
- db/seeds.rb
'Added pictures to Booking Index and Meal Show'
> Cloudinary integration

- app/controllers/meals_controller.rb
- app/views/bookings/show.html.erb
- app/views/meals/show.html.erb
Hey guys, users were no able to book a meal for a second time, even when the booking date had already passed. Now they can book again the same meal but only when they don't have pending (future) bookings with that meal.
> book a meal previously booked

- app/controllers/bookings_controller.rb
- app/controllers/reviews_controller.rb
- app/models/meal.rb
- app/views/bookings/_review_form.html.erb
- app/views/bookings/show.html.erb
- app/views/meals/show.html.erb
- app/views/reviews/_review_form.html.erb
- db/seeds.rb
Fix review path, added latest seed with Cloudinary images, fixed hours and days in meal show view.
> Fix review path

- app/views/meals/show.html.erb
- db/seeds.rb
Seeds now includes real Mexico City addresses and 3 pictures per meal (Cloudinary). One of them, the first one, is related to the subject. The others are random. Already created 15 meal records in DB.
> Seeds file with pictures & real addresses

- app/controllers/meals_controller.rb
- app/views/bookings/show.html.erb
- app/views/meals/show.html.erb
- db/seeds.rb
Just some minor corrections. A syntax error in bookings#show, a broken link in meal#show, updated the logic to check if a user is able or not to create a new booking on a meal, and now meal#show display open hrs in "hr:min" format. That was part of the issue of the booking form not showing only the exact open hrs available.
> Minor fixes

- app/controllers/meals_controller.rb
- app/views/bookings/show.html.erb
- app/views/meals/show.html.erb
- db/seeds.rb
Issue with bookings form not showing the exact available open hrs for the meal was related to meals having open hours not allocated in 30 min spaces (12:00, 12:30, 1:00...). 
Also corrected other minor issues related to the bookings & reviews creations. We're only creating 10 users and 15 meals but bookings and reviews were being assigned users and meals IDs with a bigger range than that (1..15+)
> Valid open/close hrs in seed

- app/controllers/application_controller.rb
- app/views/bookings/show.html.erb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- config/routes.rb
Fixed some booking view issues...turns out sign up was creating users without names and that's why it wasn't displaying. Fixed that and a couple other minor things in the commit
> Booking view fixes

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/meals_controller.rb
- app/controllers/reviews_controller.rb
- app/policies/application_policy.rb
- app/policies/booking_policy.rb
- app/policies/meal_policy.rb
- app/policies/review_policy.rb
- app/views/meals/home.html.erb
- app/views/meals/new.html.erb
- app/views/meals/show.html.erb
- test/policies/booking_policy_test.rb
- test/policies/meal_policy_test.rb
- test/policies/review_policy_test.rb
Guys, implemented all changes needed for pundit and I added images to the home page cause it wasn't loading properly.
> Pundit implementation

- app/views/bookings/eaters.html.erb
- app/views/bookings/show.html.erb
- app/views/meals/offered.html.erb
- app/views/meals/show.html.erb
- app/views/reviews/_review_form.html.erb
Fixes to booking show and meal show view...as well as manage meals view enhancements.
> Other fixes

- app/controllers/meals_controller.rb
- app/views/meals/show.html.erb
- config/environments/production.rb
- config/initializers/geocoder.rb
- db/seeds.rb
Minor Improvements to Show Meal + Seeds + Heroku/Cluodinary active_storage
> Show meal and 

- db/seeds.rb
The seed now contain only addresses that the current location API can find
> seed with only valid addresses

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/views/meals/home.html.erb
> first draft of cards component CSS

- app/views/meals/home.html.erb
Get back to the last working homepage
> working homrpage

- app/views/meals/home.html.erb
Second attempt to restore our homepage to the last working version
> working homepage

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/application.html.erb
- app/views/meals/home.html.erb
> add footer

- app/views/meals/partials/_create_edit_form.html.erb
Just to make the new/edit form for the meals look a little better
> small upgrade to meal new/edit form

- app/views/meals/offered.html.erb
- app/views/meals/partials/_create_edit_form.html.erb
> Modify offered view

- app/assets/stylesheets/components/_cards.scss
- app/views/bookings/index.html.erb
- app/views/bookings/show.html.erb
> Bookings front end 2

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/config/_fonts.scss
- app/models/review.rb
- app/views/bookings/partials/_new_edit_form.html.erb
- app/views/meals/show.html.erb
- app/views/reviews/_review_form.html.erb
- app/views/reviews/new.html.erb
> revamped views & new font

- app/assets/stylesheets/pages/_home.scss
Field to input date in the booking form was overflowing the form itself. That was corrected
> corrected date field in booking form

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
Footer now sticks to the bottom of the page
> Fix footer

- app/assets/stylesheets/components/_cards.scss
- app/views/meals/home.html.erb
Standardize the size of the images and made the entire card clickable instead of just the title
> Index cards

- app/views/meals/show.html.erb
added bootstrap container & meal price to the view
> Update meal show

- app/assets/stylesheets/components/_cards.scss
- app/views/bookings/index.html.erb
- app/views/meals/offered.html.erb
Standardized meal cards throughout the app. Same style is used on homepage, bookings and meals offered
> Meal cards
